### ISSUE TITLE
allow pandas >=2.0.1

### ISSUE THREAD

**Issue by aka-rabbi-inv** [aws-samples/amazon-textract-textractor#234]
in my project I want to use this package but getting this error( with poetry)
```
...
Because no versions of pandas match >2.0.1,<2.0.2 || >2.0.2,<2.0.3 || >2.0.3,<3.0.0
 and pandas (2.0.1) depends on numpy (>=1.23.2), pandas (>=2.0.1,<2.0.2 || >2.0.2,<2.0.3 || >2.0.3,<3.0.0) requires numpy (>=1.23.2).
And because pandas (2.0.2) depends on numpy (>=1.23.2)
 and pandas (2.0.3) depends on numpy (>=1.23.2), pandas (>=2.0.1,<3.0.0) requires numpy (>=1.23.2).
Because no versions of amazon-textract-textractor match >1.3.2,<2.0.0
 and amazon-textract-textractor (1.3.2) depends on numpy (>=1.21.0,<1.22.0), amazon-textract-textractor (>=1.3.2,<2.0.0) requires numpy (>=1.21.0,<1.22.0).
Thus, amazon-textract-textractor (>=1.3.2,<2.0.0) is incompatible with pandas (>=2.0.1,<3.0.0).
```

would be grateful if this issue can be resolved

**Comment by tb102122** [comment]
@schadem the issue reported is due to the version pin of numpy.
I am not sure why this version was introduced in the following files.

https://github.com/aws-samples/amazon-textract-textractor/blob/e5051e53c062f8af60ec5fa9445affb0c7485f7b/extras/pandas.txt#L1C8-L1C8

https://github.com/aws-samples/amazon-textract-textractor/blob/e5051e53c062f8af60ec5fa9445affb0c7485f7b/extras/pandas.txt#L1C8-L1C8

https://github.com/aws-samples/amazon-textract-textractor/blob/e5051e53c062f8af60ec5fa9445affb0c7485f7b/extras/dev.txt#L1
