### ISSUE TITLE
Assertion error for larger PDF documents

### ISSUE THREAD

**Issue by rnschmidt** [aws-samples/amazon-textract-textractor#306]
I am getting this error when I try processing larger (50+ page) PDFs:

` assert len(pages) == response["DocumentMetadata"]["Pages"]
`

https://github.com/aws-samples/amazon-textract-textractor/blob/3398444a0516dbdd2d78981e66eed3c41bca9e9a/textractor/parsers/response_parser.py#L1177

This works without error for smaller 1-5 page documents that I've tested. I don't see anything obvious in my implementation that would cause this issue. Since this is throwing an error based on a difference in the number of pages returned in the textractor document and the aws response, is this a bug with textractor itself?

**Comment by Belval** [comment]
Hi, could you share the version of Textractor `pip freeze | grep textractor`, a code snippet showing how you call Textractor and the asset if possible? This would help greatly in troubleshooting the issue.

**Comment by rnschmidt** [comment]
`amazon-textract-textractor==1.7.1`

```
from textractor.entities.document import Document as TDocument

raw_data = None
try:
    raw_data = RawExtractedData.objects.get(document=document)
except RawExtractedData.DoesNotExist:
    logger.info("RawExtractedData does not exist for document %s", document_id)

doc = None
if raw_data:
    doc = TDocument.open(raw_data.data)
```

**Comment by Belval** [comment]
Ok so usually this error is caused by only fetching a partial response from the Textract API. `Document.open` is failing because it detects that the response should have N pages but contains <N. To fix this you should check how `raw_data.data` gets the results from the Textract API, it's probably not checking for `NextToken` and returning the partial response as the full one.
